---
# hackathonMission: define the ending Ansible tasks to install ChRIS to podman locally
# hackathonColumn: Automate ChRIS install
# hackathonLabel: create_after_tasks
# hackathonLabels: ansible,yml

