kind: Kustomization

namespace: ${NAMESPACE}

configMapGenerator:
- name: chris-config
  env: secrets/.chris.env
- name: chris-db-config
  env: secrets/.chris_db.env
- name: chris-store-config
  env: secrets/.chris_store.env
- name: chris-store-db-config
  env: secrets/.chris_store_db.env
- name: pfcon-config
  env: secrets/.pfcon.env
- name: pman-config
  env: secrets/.pman.env
- name: swift-config
  env: secrets/.swift_service.env

resources:
- resources/chris.yaml
- resources/worker.yaml
- resources/worker-periodic.yaml
- resources/scheduler.yaml
- resources/chris-db.yaml
- resources/chris-store.yaml
- resources/chris-store-db.yaml
- resources/rabbitmq.yaml
- resources/swift.yaml
- resources/pfcon.yaml
- resources/pman.yaml

vars:
- name: CHRIS_DB_SERVICE_NAME
  objref:
    kind: Service
    name: chris-db
    apiVersion: v1
- name: CHRIS_STORE_SERVICE_NAME
  objref:
    kind: Service
    name: chris-store
    apiVersion: v1
- name: CHRIS_STORE_DB_SERVICE_NAME
  objref:
    kind: Service
    name: chris-store-db
    apiVersion: v1
- name: SWIFT_SERVICE_NAME
  objref:
    kind: Service
    name: swift
    apiVersion: v1
- name: QUEUE_SERVICE_NAME
  objref:
    kind: Service
    name: queue
    apiVersion: v1
- name: PMAN_SERVICE_NAME
  objref:
    kind: Service
    name: pman
    apiVersion: v1
