apiVersion: v1
kind: PersistentVolume
metadata:
  name: chrisdb
  labels:
    volume: chrisdb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Gi
  nfs:
    # The ChRIS DB storage dir becomes a path in the NFS drive
    server: ${NFS_SERVER}
    path: ${STORAGEBASE}/chrisDB
