apiVersion: v1
kind: PersistentVolume
metadata:
  name: queuedb
  labels:
    volume: queuedb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 40Gi
  nfs:
    # The ChRIS async queue storage dir becomes a path in the NFS drive
    server: ${NFS_SERVER}
    path: ${STORAGEBASE}/queueDB
