apiVersion: v1
kind: PersistentVolume
metadata:
  name: storebase
  labels:
    volume: storebase
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 40Gi
  nfs:
    # The key store in pfcon becomes a path in the NFS drive
    server: ${NFS_SERVER}
    path: ${STOREBASE}
