apiVersion: v1
kind: PersistentVolume
metadata:
  name: storedb
  labels:
    volume: storedb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 80Gi
  nfs:
    # The ChRIS store DB storage dir becomes a path in the NFS drive
    server: ${NFS_SERVER}
    path: ${STORAGEBASE}/storeDB
