apiVersion: v1
kind: PersistentVolume
metadata:
  name: swiftdb
  labels:
    volume: swiftdb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 400Gi
  nfs:
    # The Swift object storage dir becomes a path in the NFS drive
    server: ${NFS_SERVER}
    path: ${STORAGEBASE}/swiftDB
