apiVersion: v1
kind: PersistentVolume
metadata:
  name: chrisdb
  labels:
    volume: chrisdb
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  # Mount a physical dir in the HOST onto the ChRIS DB. This dir
  # is given by the STORAGEBASE env variable substitution.
  hostPath:
    path: ${STORAGEBASE}/chrisDB
