apiVersion: v1
kind: PersistentVolume
metadata:
  name: swiftdb
  labels:
    volume: swiftdb
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  # Mount a physical dir in the HOST onto the Swift object storage. This dir
  # is given by the STORAGEBASE env variable substitution.
  hostPath:
    path: ${STORAGEBASE}/swiftDB
