---
# hackathonTitle: create an Ansible Playbook to setup the dev container locally. 
# hackathonColumn: Automate dev
# hackathonLabels: ansible,yml
# TODO: define the playbook to run locally
- name: Install the ChRIS containers locally in podman with Ansible
  connection: local
  hosts: localhost
  

  # TODO: Run the chris_defaults role to load the ChRIS related variables. 
  roles:
    - chris_defaults
    # TODO: Now run the chris_dev role to install the dev container to podman. 
    - chris_dev

