---
# hackathonMission: create an Ansible Playbook to setup the scheduler container locally
# hackathonColumn: Automate scheduler
# hackathonLabels: ansible,yml
# TODO: define the playbook to run locally
- name: Install the ChRIS containers locally in podman with Ansible
  connection: local
  hosts: localhost


  # TODO: Run the chris_defaults role to load the ChRIS related variables. 
  roles:
    - chris_defaults
    # TODO: Now run the chris_scheduler role to install the scheduler container to podman. 
    - chris_scheduler

