---
# hackathonTitle: create an Ansible Playbook to setup the main ChRIS plugins. 
# hackathonColumn: Automate ChRIS install
# hackathonLabels: ansible,yml
# TODO: Define the playbook to run locally. 
- name: Install only the ChRIS plugins locally in podman with Ansible
  connection: local
  hosts: localhost


  # TODO: Run the chris_plugins role to load the main ChRIS plugins. 
  roles:
    - chris_plugins
