apiVersion: v1
kind: Service
metadata:
  name: chris-store-db
  labels:
    app: chris-store-db
    env: production
spec:
  selector:
    app: chris-store-db
    env: production
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-store-db
  labels:
    app: chris-store-db
    env: production
spec:
  replicas: 1  # stateful service, so only a single replica must be used
  selector:
    matchLabels:
      app: chris-store-db
      env: production
  template:
    metadata:
      name: chris-store-db
      labels:
        app: chris-store-db
        env: production
    spec:
      containers:
        - name: chris-store-db
          image: postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: chris-store-db-config
          volumeMounts:
            - name: storedb
              mountPath: "/var/lib/postgresql/data"
      # Mount a persistent volume onto ChRIS DB
      volumes:
        - name: storedb
          persistentVolumeClaim:
            claimName: storedb
