apiVersion: v1
kind: Service
metadata:
  name: chris
  labels:
    app: chris
    env: production
spec:
  type: NodePort
  selector:
    app: chris
    env: production
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris
  labels:
    app: chris
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chris
      env: production
  template:
    metadata:
      name: chris
      labels:
        app: chris
        env: production
    spec:
      initContainers:
        - name: chris-waitfor-swift
          image: busybox:1.32
          command: [ "sh", "-c", "until wget --spider -S -T 2 http://$(SWIFT_SERVICE_NAME):8080/info 2>&1 | grep '200 OK'; do echo waiting for Swift storage; sleep2; done" ]
        - name: chris-waitfor-store
          image: busybox:1.32
          command: [ "sh", "-c", "until wget --spider -S -T 2 http://$(CHRIS_STORE_SERVICE_NAME):8010/api/v1/ 2>&1 | grep '200 OK'; do echo waiting for ChRIS store; sleep2; done" ]
      containers:
        - name: chris
          image: fnndsc/chris
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: $(CHRIS_DB_SERVICE_NAME)
            - name: DATABASE_PORT
              value: "5432"
            - name: CHRIS_STORE_URL
              value: http://$(CHRIS_STORE_SERVICE_NAME):8010/api/v1/
            - name: SWIFT_AUTH_URL
              value: http://$(SWIFT_SERVICE_NAME):8080/auth/v1.0
            - name: CELERY_BROKER_URL
              value: amqp://$(QUEUE_SERVICE_NAME):5672
          envFrom:
            - configMapRef:
                name: chris-config
            - configMapRef:
                name: chris-db-config
            - configMapRef:
                name: swift-config
