apiVersion: v1
kind: Service
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: production
spec:
  type: NodePort
  selector:
    app: pfcon
    env: production
  ports:
    - port: 5005
      targetPort: 5005
      nodePort: 30005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfcon
  labels:
    app: pfcon
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfcon
      env: production
  template:
    metadata:
      name: pfcon
      labels:
        app: pfcon
        env: production
    spec:
      initContainers:
        - name: init-pfcon
          image: busybox:1.32
          command: [ "sh", "-c", "until wget --spider -S -T 2 http://$(PMAN_SERVICE_NAME):5010/api/v1/ 2>&1 | grep '200 OK'; do echo waiting for pman; done" ]
      containers:
        - name: pfcon
          image: fnndsc/pfcon
          ports:
            - containerPort: 5005
          env:
            - name: COMPUTE_SERVICE_URL
              value: http://$(PMAN_SERVICE_NAME):5010/api/v1/
          envFrom:
            - configMapRef:
                name: pfcon-config
          volumeMounts:
            - name: storebase
              mountPath: "/home/localuser/storeBase"
      # Mount a persistent volume onto pfcon's key store (shared data volume with plugins)
      volumes:
        - name: storebase
          persistentVolumeClaim:
            claimName: storebase
