apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    app: queue
    env: production
spec:
  selector:
    app: queue
    env: production
  ports:
    - port: 5672
      targetPort: 5672

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
    env: production
spec:
  replicas: 1  # stateful service, so only a single replica must be used
  selector:
    matchLabels:
      app: queue
      env: production
  template:
    metadata:
      name: queue
      labels:
        app: queue
        env: production
    spec:
      containers:
        - name: queue
          image: rabbitmq:3
          ports:
            - containerPort: 5672
          volumeMounts:
            - name: queuedb
              mountPath: "/var/lib/rabbitmq"
      # Mount a persistent volume onto the async queue
      volumes:
        - name: queuedb
          persistentVolumeClaim:
            claimName: queuedb
